### ISSUE TITLE
Vraag

### ISSUE THREAD

**Issue by Brinkhuis** [misjamikkers/Meetup_Informatieberaad#1]
Ha @misjamikkers ,

Interessante blog, ik heb hem met belangstelling gelezen! Bij het stukje over de DAG "Mediator" staat boven de eerste grafiek/analyse:

> Wanneer we de variable Teamsterkte niet opnemen in de analyse, dan zien we een vrij sterke correlatie tussen Teamsterkte en het behaalde aantal Punten.

Als ik het goed begrijp toont de grafiek (dan) juist een vrij sterke correlatie tussen __*Budgetten*__ en het behaalde aantal Punten. Typo? Of heb ik iets gemist?

Groet, René.

**Comment by misjamikkers** [comment]
Hoi, @Brinkhuis

Je hebt gelijk. Verbetering is aangebracht. Bedankt voor de issue!
